language: python
python:
  - 3.6
  - 3.7
  - 3.8

# Build only tagged commits
if: tag IS present

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes
  - conda config --set anaconda_upload no
  - conda config --append channels conda-forge

install:
  - conda update -q conda
  - conda install -q python=$TRAVIS_PYTHON_VERSION conda-build anaconda-client

script:
  - conda build conda-recipe

deploy:
  provider: script
  script: anaconda -t $ANACONDA_TOKEN upload $HOME/miniconda/conda-bld/**/jungfrau_utils-*.tar.bz2
  on:
    branch: master
    tags: true

notifications:
  email: false
