name: Deployment

on:
  push:
    tags:
      - '*'

jobs:
  publish-conda-package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      run: |
        $CONDA/bin/conda config --system --remove channels defaults
        $CONDA/bin/conda config --append channels conda-forge
        $CONDA/bin/conda install --quiet --yes conda-build anaconda-client conda-libmamba-solver
        $CONDA/bin/conda config --set solver libmamba

    - name: Build
      run: |
        $CONDA/bin/conda build --no-anaconda-upload conda-recipe

    - name: Upload
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        $CONDA/bin/anaconda --token $ANACONDA_TOKEN upload $($CONDA/bin/conda build ./conda-recipe --output)
