name: Deployment

on:
  push:
    tags:
      - '*'

jobs:
  publish-conda-package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        channels: conda-forge
        conda-remove-defaults: true
        activate-environment: ""

    - name: Install required conda packages
      run: |
        $CONDA/bin/conda install --quiet --yes conda-build anaconda-client

    - name: Build
      run: |
        $CONDA/bin/conda build --no-anaconda-upload conda-recipe

    - name: Upload
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        $CONDA/bin/anaconda --token $ANACONDA_TOKEN upload $($CONDA/bin/conda build ./conda-recipe --output)
